### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by abecaw** [gruvin/OctoPrint-WebcamTab#2]
Here is the "plugin softwareupdate_console.log..
[plugin_softwareupdate_console.log](https://github.com/gruvin/OctoPrint-WebcamTab/files/5682512/plugin_softwareupdate_console.log)

**Comment by Lunik971** [comment]
hello,

I'm in the same case, the file to download : https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip doen't exist :/

**Comment by abecaw** [comment]
Yep, When I was on GitHub I found the clad but haven’t had time to try it. I suspect that it will fail because it’s the same code that the app that fails runs. If it works I’ll send it to you.   
  
  
  
  
  
  
David M. Fox
 ABEC(AW)
 USN Ret.   
      
  

  
  
>

**Comment by dams74** [comment]
Hello
I've the same problem
`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
ERROR: HTTP error 404 while getting https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
ERROR: Could not install requirement https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip because of error 404 Client Error: Not Found for url: https://codeload.github.com/malnvenshorn/OctoPrint-WebcamTab/zip/0.2.0
ERROR: Could not install requirement https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/malnvenshorn/OctoPrint-WebcamTab/zip/0.2.0 for URL https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.`

plugin_sofware update log
`2020-12-27 19:03:25,861 > Successfully built UI-Customizer
2020-12-27 19:03:25,865 > Installing collected packages: UI-Customizer
2020-12-27 19:03:25,867 > Successfully installed UI-Customizer-0.1.1.8
2020-12-27 19:05:41,309   /home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip --no-cache-dir
2020-12-27 19:05:46,411 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2020-12-27 19:05:46,414 > Collecting https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
2020-12-27 19:05:47,142 ! ERROR: HTTP error 404 while getting https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
2020-12-27 19:05:47,148 ! ERROR: Could not install requirement https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip because of error 404 Client Error: Not Found for url: https://codeload.github.com/malnvenshorn/OctoPrint-WebcamTab/zip/0.2.0
2020-12-27 19:05:47,150 ! ERROR: Could not install requirement https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/malnvenshorn/OctoPrint-WebcamTab/zip/0.2.0 for URL https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
2020-12-27 19:06:46,504   /home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip --no-cache-dir
2020-12-27 19:06:50,964 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2020-12-27 19:06:50,967 > Collecting https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
2020-12-27 19:06:51,603 ! ERROR: HTTP error 404 while getting https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip
2020-12-27 19:06:51,610 ! ERROR: Could not install requirement https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip because of error 404 Client Error: Not Found for url: https://codeload.github.com/malnvenshorn/OctoPrint-WebcamTab/zip/0.2.0
2020-12-27 19:06:51,613 ! ERROR: Could not install requirement https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/malnvenshorn/OctoPrint-WebcamTab/zip/0.2.0 for URL https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/0.2.0.zip`

octoprint log
`2020-12-27 18:55:16,264 - octoprint.plugins.softwareupdate - INFO - Starting update of octolapse to v0.4.1...
2020-12-27 18:55:18,838 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-12-27 18:55:18,844 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-12-27 18:55:18,846 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-12-27 19:01:01,093 - octoprint.plugins.softwareupdate - INFO - Update of octolapse to v0.4.1 successful!
2020-12-27 19:01:01,563 - octoprint.plugins.tracking - INFO - Sent tracking event update_successful, payload: {'to_version': 'v0.4.1', 'from_version': '0.4.0', 'target': u'octolapse'}
2020-12-27 19:01:01,580 - octoprint.plugins.softwareupdate - INFO - Starting update of uicustomizer to 0.1.1.8...
2020-12-27 19:01:17,161 - octoprint.plugins.softwareupdate - INFO - Update of uicustomizer to 0.1.1.8 successful!
2020-12-27 19:01:17,605 - octoprint.plugins.tracking - INFO - Sent tracking event update_successful, payload: {'to_version': '0.1.1.8', 'from_version': '0.1.1.6', 'target': u'uicustomizer'}
2020-12-27 19:01:17,728 - octoprint.plugins.softwareupdate - INFO - Starting update of webcamtab to 0.2.0...
2020-12-27 19:01:25,118 - octoprint.plugins.softwareupdate - ERROR - Update of webcamtab can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 1788, in _perform_update
    target, populated_check, target_version, log_cb=self._log, online=online
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 144, in perform_update
    "Error while executing pip install", (stdout, stderr)
UpdateError: Error while executing pip install
2020-12-27 19:01:25,428 - octoprint.plugins.tracking - INFO - Sent tracking event update_failed, payload: {'to_version': '0.2.0', 'from_version': '0.1.2', 'target': u'webcamtab'}
2020-12-27 19:02:37,644 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2020-12-27 19:02:58,500 - octoprint.plugins.softwareupdate - INFO - Starting update of uicustomizer to 0.1.1.8...
2020-12-27 19:03:16,494 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2020-12-27 19:03:25,870 - octoprint.plugins.softwareupdate - INFO - Update of uicustomizer to 0.1.1.8 successful!
2020-12-27 19:03:26,522 - octoprint.plugins.tracking - INFO - Sent tracking event update_successful, payload: {'to_version': u'0.1.1.8', 'from_version': '0.1.1.6', 'target': u'uicustomizer'}
2020-12-27 19:03:26,600 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2020-12-27 19:03:26,609 - octoprint.plugins.softwareupdate - INFO - Restarting...
2020-12-27 19:03:26,962 - octoprint.server - INFO - Shutting down...
2020-12-27 19:03:27,368 - octoprint.server - INFO - Calling on_shutdown on plugins
2020-12-27 19:03:27,370 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2020-12-27 19:03:27,399 - octoprint.events - INFO - Event loop shut down
2020-12-27 19:03:28,218 - octoprint.plugins.tracking - INFO - Sent tracking event shutdown, payload: {}
2020-12-27 19:03:28,271 - octoprint.server - INFO - Goodbye!
2020-12-27 19:03:33,077 - octoprint.startup - INFO - ******************************************************************************
2020-12-27 19:03:33,082 - octoprint.startup - INFO - Starting OctoPrint 1.5.2
2020-12-27 19:03:33,083 - octoprint.startup - INFO - ******************************************************************************
2020-12-27 19:03:34,424 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2020-12-27 19:03:34,569 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2020-12-27 19:03:34,572 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 8.8.8.8:53 is working
2020-12-27 19:03:34,574 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2020-12-27 19:03:34,928 - octoprint.startup - INFO - Blacklist processing done, adding 12 blacklisted plugin versions: roomtemp (any), GcodeEditor (0.1.1), GcodeEditor (0.2.0), GcodeEditor (0.2.1), GcodeEditor (0.2.2), GcodeEditor (0.2.3), GcodeEditor (0.2.4), GcodeEditor (0.2.5), GcodeEditor (0.2.6), GcodeEditor (0.2.8), gcodeleveling (0.1.0), gcodeleveling (0.1.1)
2020-12-27 19:03:35,008 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-12-27 19:03:38,715 - octoprint.startup - INFO - Added settings overlay from plugin dashboard
2020-12-27 19:03:38,743 - octoprint.plugin.core - INFO - Found 22 plugin(s) providing 22 mixin implementations, 51 hook handlers
2020-12-27 19:03:39,194 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2020-12-27 19:03:39,250 - octoprint.server - INFO - Intermediary server started
2020-12-27 19:03:39,323 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2020-12-27 19:03:40,383 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2020-12-27 19:03:40,393 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: u"Need(method='role', value=u'plugin_action_command_notification_show')")
2020-12-27 19:03:40,394 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: u"Need(method='role', value=u'plugin_action_command_notification_clear')")
2020-12-27 19:03:40,398 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: u"Need(method='role', value=u'plugin_action_command_prompt_interact')")
2020-12-27 19:03:40,401 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: u"Need(method='role', value=u'plugin_announcements_read')")
2020-12-27 19:03:40,405 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: u"Need(method='role', value=u'plugin_announcements_manage'), Need(method='role', value=u'plugin_announcements_read')")
2020-12-27 19:03:40,413 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: u"Need(method='role', value=u'plugin_appkeys_admin')")
2020-12-27 19:03:40,418 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: u"Need(method='role', value=u'plugin_backup_access')")
2020-12-27 19:03:40,422 - octoprint.server - INFO - Added new permission from plugin dashboard: PLUGIN_DASHBOARD_ADMIN (needs: u"Need(method='role', value=u'plugin_dashboard_admin')")
2020-12-27 19:03:40,425 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: u"Need(method='role', value=u'plugin_firmware_check_display')")
2020-12-27 19:03:40,428 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: u"Need(method='role', value=u'plugin_logging_manage')")
2020-12-27 19:03:40,432 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: u"Need(method='role', value=u'plugin_pi_support_check')")
2020-12-27 19:03:40,436 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: u"Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-12-27 19:03:40,439 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: u"Need(method='role', value=u'plugin_pluginmanager_install'), Need(method='role', value=u'plugin_pluginmanager_manage')")
2020-12-27 19:03:40,442 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: u"Need(method='role', value=u'plugin_softwareupdate_check')")
2020-12-27 19:03:40,443 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: u"Need(method='role', value=u'plugin_softwareupdate_update')")
2020-12-27 19:03:40,445 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CONFIGURE (needs: u"Need(method='role', value=u'plugin_softwareupdate_configure')")
2020-12-27 19:03:41,319 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2020-12-27 19:03:43,581 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-12-27 19:03:45,645 - octoprint.util.pip - INFO - Version of pip is 19.3.1
2020-12-27 19:03:45,648 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-12-27 19:03:45,650 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-12-27 19:03:45,680 - octoprint.plugin.core - INFO - Initialized 22 plugin implementation(s)
2020-12-27 19:03:45,744 - octoprint.plugin.core - INFO - 22 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Dashboard (1.16.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_dashboard
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  DisplayLayerProgress Plugin (1.24.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress
|  Error Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  File Check (2020.8.7) (bundled) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_file_check
|  Firmware Check (2020.9.23) (bundled) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_firmware_check
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/gcodeviewer
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  Octolapse (0.4.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  UI Customizer (0.1.1.8) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_uicustomizer
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Webcam Tab (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_webcamtab
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-12-27 19:03:45,825 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 900.0
|      ram: 915730432
|  os:
|      bits: 32
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 2 Model B Rev 1.1
|          octopi_version: 0.17.0
|          throttle_state: '0x0'
|  python:
|      pip: 19.3.1
|      version: 2.7.16
|      virtualenv: /home/pi/oprint
2020-12-27 19:03:45,864 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2020-12-27 19:03:45,945 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2020-12-27 19:03:49,552 - octoprint.server - INFO - Shutting down intermediary server...
2020-12-27 19:03:49,781 - octoprint.server - INFO - Intermediary server shut down
2020-12-27 19:03:49,787 - octoprint.events - INFO - Processing startup event, this is our first event
2020-12-27 19:03:49,790 - octoprint.events - INFO - Adding 2 events to queue that were held back before startup event
2020-12-27 19:03:49,812 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2020-12-27 19:03:49,827 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2020-12-27 19:03:49,947 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2020-12-27 19:03:49,949 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2020-12-27 19:03:50,083 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2020-12-27 19:03:50,083 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2020-12-27 19:03:51,319 - octoprint.plugins.tracking - INFO - Sent tracking event system_unthrottled, payload: {u'throttled_mask': 0, u'throttled_voltage_now': False, u'throttled_voltage_past': False, u'throttled_overheat_now': False, u'throttled_now': False, u'throttled_past': False, u'throttled_overheat_past': False}
2020-12-27 19:03:55,234 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2020-12-27 19:03:55,601 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-12-27 19:03:55,605 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-12-27 19:03:55,608 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-12-27 19:03:55,830 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2020-12-27 19:03:56,892 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._http._tcp.local.' for _http._tcp.local.
2020-12-27 19:03:57,736 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._octoprint._tcp.local.' for _octoprint._tcp.local.
2020-12-27 19:03:57,758 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2020-12-27 19:03:57,854 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2020-12-27 19:03:58,161 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2020-12-27 19:03:58,542 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.184
2020-12-27 19:03:59,823 - octoprint.server.util.flask - INFO - Passively logging in user Dams from ::ffff:192.168.1.184
2020-12-27 19:03:59,873 - octoprint.access.users - INFO - Logged in user: Dams
2020-12-27 19:04:00,022 - octoprint.server.util.sockjs - INFO - User Dams logged in on the socket from client ::ffff:192.168.1.184
2020-12-27 19:04:00,716 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2020-12-27 19:04:00,736 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-12-27 19:04:00,818 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-12-27 19:04:00,946 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 4.2GB. That is considered sufficient for updating.
2020-12-27 19:04:01,833 - octoprint.plugins.dashboard - INFO - Dashboard started
2020-12-27 19:04:01,851 - octoprint.plugins.uicustomizer - INFO - UI Customizer is initialized.
2020-12-27 19:04:02,579 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {'octoprint_uptime': 25}
2020-12-27 19:04:03,201 - octoprint.plugins.tracking - INFO - Sent tracking event startup, payload: {u'python': '2.7.16', u'os': u'linux', u'ram': 915730432, u'octopi_version': u'0.17.0', u'version': u'1.5.2', u'pip': '19.3.1', u'cores': 4, u'freq': 900.0, u'pi_model': u'Raspberry Pi 2 Model B Rev 1.1', u'bits': 32}
2020-12-27 19:04:03,749 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {u'python': '2.7.16', u'os': u'linux', u'ram': 915730432, u'octopi_version': u'0.17.0', u'version': u'1.5.2', u'plugins': u'displaylayerprogress:1.24.0,uicustomizer:0.1.1.8,webcamtab:0.1.2,dashboard:1.16.3,octolapse:0.4.1', u'pip': '19.3.1', u'cores': 4, u'freq': 900.0, u'pi_model': u'Raspberry Pi 2 Model B Rev 1.1', u'bits': 32}
2020-12-27 19:04:04,273 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.117/'}
2020-12-27 19:04:05,175 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2020-12-27 19:04:07,601 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.7
2020-12-27 19:04:10,266 - octoprint.server.util.flask - INFO - Passively logging in user Dams from ::ffff:192.168.1.184
2020-12-27 19:04:10,268 - octoprint.access.users - INFO - Logged in user: Dams
2020-12-27 19:05:07,606 - octoprint.server.preemptive_cache - INFO - ... done in 63.33s
2020-12-27 19:05:07,737 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 22.97ms
2020-12-27 19:05:07,765 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 20.32ms
2020-12-27 19:05:07,795 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 21.80ms
2020-12-27 19:05:07,839 - octoprint.server.util.flask - INFO - Passively logging in user Dams from ::ffff:192.168.1.184
2020-12-27 19:05:07,841 - octoprint.access.users - INFO - Logged in user: Dams
2020-12-27 19:05:08,082 - octoprint.server.util.flask - INFO - Passively logging in user Dams from ::ffff:192.168.1.184
2020-12-27 19:05:08,086 - octoprint.access.users - INFO - Logged in user: Dams
2020-12-27 19:05:10,140 - octoprint.server.util.sockjs - INFO - Client connection closed: ::ffff:192.168.1.184
2020-12-27 19:05:10,170 - octoprint.server.util.flask - INFO - Passively logging in user Dams from ::ffff:192.168.1.7
2020-12-27 19:05:10,176 - octoprint.access.users - INFO - Logged in user: Dams
2020-12-27 19:05:13,979 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 21.63ms
2020-12-27 19:05:14,020 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 22.96ms
2020-12-27 19:05:14,034 - octoprint.server.util.sockjs - INFO - User Dams logged in on the socket from client ::ffff:192.168.1.7
2020-12-27 19:05:15,788 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.184
2020-12-27 19:05:15,878 - octoprint.server.util.flask - INFO - Passively logging in user Dams from ::ffff:192.168.1.184
2020-12-27 19:05:15,880 - octoprint.access.users - INFO - Logged in user: Dams
2020-12-27 19:05:22,735 - octoprint.server.util.sockjs - INFO - User Dams logged in on the socket from client ::ffff:192.168.1.184
2020-12-27 19:05:23,903 - tornado.access - WARNING - 404 GET /plugin/octolapse/getSnapshot?file_type=thumbnail&camera_guid=354def78-9eea-409a-ad23-ee966dfff4ba&apikey=&time=1609095922985 (::ffff:192.168.1.184) 6.10ms
2020-12-27 19:05:23,920 - tornado.access - WARNING - 404 GET /plugin/octolapse/getSnapshot?file_type=snapshot&camera_guid=354def78-9eea-409a-ad23-ee966dfff4ba&apikey=&time=1609095922985 (::ffff:192.168.1.184) 7.83ms
2020-12-27 19:05:41,274 - octoprint.plugins.softwareupdate - INFO - Starting update of webcamtab to 0.2.0...
2020-12-27 19:05:47,153 - octoprint.plugins.softwareupdate - ERROR - Update of webcamtab can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 1788, in _perform_update
    target, populated_check, target_version, log_cb=self._log, online=online
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 144, in perform_update
    "Error while executing pip install", (stdout, stderr)
UpdateError: Error while executing pip install
2020-12-27 19:05:47,504 - octoprint.plugins.tracking - INFO - Sent tracking event update_failed, payload: {'to_version': '0.2.0', 'from_version': '0.1.2', 'target': u'webcamtab'}
2020-12-27 19:06:10,591 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 31.65ms
2020-12-27 19:06:46,469 - octoprint.plugins.softwareupdate - INFO - Starting update of webcamtab to 0.2.0...
2020-12-27 19:06:51,616 - octoprint.plugins.softwareupdate - ERROR - Update of webcamtab can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 1788, in _perform_update
    target, populated_check, target_version, log_cb=self._log, online=online
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 144, in perform_update
    "Error while executing pip install", (stdout, stderr)
UpdateError: Error while executing pip install
2020-12-27 19:06:51,946 - octoprint.plugins.tracking - INFO - Sent tracking event update_failed, payload: {'to_version': '0.2.0', 'from_version': '0.1.2', 'target': u'webcamtab'}
2020-12-27 19:07:10,045 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 32.21ms
2020-12-27 19:08:10,506 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 26.45ms
2020-12-27 19:09:10,010 - tornado.access - WARNING - 409 GET /api/printer (::ffff:192.168.1.51) 30.31ms`

**Comment by pstimpel** [comment]
Since no fix for the missing file was provided by the maintainer (man, how can you miss such an easy fix for 16 days), here is the workaround:

Plugin-Manager, Install from URL: 

https://github.com/gruvin/OctoPrint-WebcamTab/archive/master.zip

Restart Octoprint, enjoy printing.

**Comment by BungeBash** [comment]
wish this fix would get updated by the 'maintainer'.  Still an issue and fails to update automatically.

**Comment by gruvin** [comment]
This should all be fixed now. I have taken ownership as the new maintainer. Please create new issues if there are new problems. Thanks.
